### ISSUE TITLE
[Bug]: Error in Console "Blocked  by CORS Policy"

### ISSUE THREAD

**Issue by Armandeus66** [arcanistzed/custom-fonts#14]
### Expected Behavior

Fonts added to Google fonts field in settings are loaded and available for use. No errors in the console.

### Current Behavior

Specified Google fonts are not loaded and cannot be used in Foundry. The console gives this error:

game:1 Access to fetch at 'https://fonts.googleapis.com/css2?family=Schoolbell&family=IM+Fell%20English&family=Cormorant+Unicase&family=Kings&family=Meddon&family=%22Font+Awesome%205%20Free%22&display=swap' from origin 'https://xxx.duckdns.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
fonts.googleapis.com/css2?family=Schoolbell&family=IM+Fell%20English&family=Cormorant+Unicase&family=Kings&family=Meddon&family=%22Font+Awesome%205%20Free%22&display=swap:1          Failed to load resource: net::ERR_FAILED

A warning is also issued when Foundry is loaded by the PF2E system if Detect Missing Fonts is enabled:

Fonts cannot be loaded, Failed to fetch

The console error occurs even if Detect Missing Fonts is disabled.

I am hosting Foundry on Oracle Cloud VCN always free tier (not on Windows 11).

### Steps to Reproduce

1. install Custom Fonts
2. add some Google Fonts in settings (Schoolbell,IM Fell English,Cormorant Unicase,Kings,Meddon,"Font Awesome 5 Free")
3. enable Detect Missing Fonts in settings
4. refresh browser
5. add text to the scene from the drawing left-side menu
6. double-click the text to open the configuration
7. go to the text tab
8. check if specified fonts are in the dropdown list of fonts

### Version

0.7.0

### Foundry VTT Version

9.269

### Operating System

Windows 11

### Browser / App

Chrome

### Game System

PF2E 3.12.2.10

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arcanistzed** [comment]
`"Font Awesome 5 Free"` is not the name of a valid Google Fonts font so Google gives me [this page](https://fonts.googleapis.com/css2?family=%22Font%20Awesome%205%20Free%22) with the error message displayed. Unfortunately, there's no way for me to know that this is why the request failed because, as you can see in the error message you posted, they don't allow scripts to fetch that error page.

You should stop seeing this error if you simply remove that font from your Google Fonts list. It should already be loaded by FVTT anyway, so there is really no need to have it there. Let me know if you have any questions or if this doesn't work for you.

**Comment by Armandeus66** [comment]
Thank you. Doing as you suggested fixed the issue.

I added Font Awesome after reading this post on Reddit that you wrote:
https://www.reddit.com/r/FoundryVTT/comments/vq71c4/how_to_change_the_basic_font_used_with_sheets/ienhdfj/

**Comment by arcanistzed** [comment]
Sorry for the confusion. That post was saying to put Font Awesome and your other fonts into the Primary Font setting, not the Google Fonts setting. But you shouldn't need to follow that post anymore because I added this as a feature to the module itself (look for the "Force Primary Font" module setting).
