### ISSUE TITLE
Adjust thickness and spacing of fonts

### ISSUE THREAD

**Issue by tagnullde** [arcanistzed/custom-fonts#5]
Is it possible to adjust the thickness and spacing of letters of a font?
I uploaded some fonts and they appear way thicker and less crisp in foundry.

Original:
![image](https://user-images.githubusercontent.com/44159008/148816978-ced712e6-6ee8-47b4-8d0a-939bea1d29a2.png)

In Foundry:
![image](https://user-images.githubusercontent.com/44159008/148817025-8c859adb-930e-4d62-a464-d383306cf46e.png)

Font Source: https://www.fontspace.com/perry-gothic-font-f1906

Regards
x41

**Comment by arcanistzed** [comment]
![image](https://user-images.githubusercontent.com/82790112/149051247-08474e08-a6d8-487e-ba09-a6036c20fd49.png)
Core Foundry adds a drop shadow and stroke around the text making it look like that. The actual glyphs are the correct size (see image above) when you remove them manually.

I'm not sure if doing this is within the scope of this module, but I'm open to thoughts.

A temporary solution would be to use a different color (such as white) since it will contrast better.

**Comment by tagnullde** [comment]
I don't think using a different color is a good workaround since it might not fit the scene (mood / background color etc.). 
If removing the drop-shadow is within the scope of this module is up to you if you. Imho it should be a Core-Feature, but so should be custom fonts. Either way - thanks for looking into it.

How did you remove them manually though? 

Regards
x41

**Comment by arcanistzed** [comment]
```
let d = canvas.drawings.placeables.filter(d => d.data.text === "Curse of Strahd")[0]
d.text.style.dropShadow = false
d.text.style.strokeThickness = 0
d.text.resolution = 10
```

**Comment by arcanistzed** [comment]
5e836bcaa95947b9fe0713f8d63c2be6ff1b1f98
